### ISSUE TITLE
'Extending Existing Widgets Tutorial' doesn't match what's in the code

### ISSUE THREAD

**Issue by tim-andes** [siteorigin/docs#107]
https://siteorigin.com/docs/widgets-bundle/getting-started/extending-existing-widgets/

Example 1 - 
`widgets/so-button-widget/so-button-widget.php` does not exist, but `wp-content/plugins/so-widgets-bundle/widgets/button/button.php` does. 

Example 2 - 
The code described below is not what is available in button.php. The 4th argument is an empty array which appears to be `$control_options`.

> In the __construct function, you'll see that the 4th argument is an array that specifies the form. The button widget has a 
> section called design and in that, a field called theme.

```php
class SiteOrigin_Widget_Button_Widget extends SiteOrigin_Widget {
	function __construct() {

		parent::__construct(
			'sow-button',
			__('SiteOrigin Button', 'so-widgets-bundle'),
			array(
				'description' => __('A powerful yet simple button widget for your sidebars or Page Builder pages.', 'so-widgets-bundle'),
				'help' => 'https://siteorigin.com/widgets-bundle/button-widget-documentation/'
			),
                        // 4th arg
			array(

			),
			false,
			plugin_dir_path(__FILE__)
		);

	}
```

The SiteOrigin_Widget class is showing the 4th argument as `$control_options`, not `$form_options`:
```php
	function __construct($id, $name, $widget_options = array(), $control_options = array(), $form_options = array(), $base_folder = false) {
		$this->form_options = $form_options;
		$this->base_folder = $base_folder;
		$this->field_ids = array();
		$this->fields = array();
```

Looks like the Widget Bundle code was reformatted and the docs were not. If you can confirm that this is the case and I'm not just missing something, I will work through the tutorial and try and piece the differences together and rewrite those portions as I go.

**Comment by AlexGStapleton** [comment]
Hi Tim,

Unfortunately, I can confirm the highlighted sections are outdated. The code snippets are however valid.

> I will work through the tutorial and try and piece the differences together and rewrite those portions as I go.

Sounds good. :)
If you run into any trouble please let me know and I'll lend a hand.

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Resolved by https://github.com/siteorigin/docs/pull/112 and https://github.com/siteorigin/docs/pull/111
