### ISSUE TITLE
Page Builder Data Dump does not work

### ISSUE THREAD

**Issue by theAlien-01** [siteorigin/docs#15]
Hi,
I enabled debug mode in wp-config.php, and added both lines of code to the end of wp-config.php.
Then I entered in admin the page that I want a Data Dump from.
Next I went to the frontend and opened the HTML source and searched for "Page Builder Data". 
Unfortunately I cannot find any dump.

Is this description still right?

**Comment by danFWD** [comment]
Very old issue but one that needs updating. The answer to the original poster's question: the data-dump actually occurs on the edit page in admin. However, there is a bug - the php is dumped as an HTML comment, but if there are HTML comments within the content itself, then it prematurely closes the opening comment tag and cause the admin page to break. 

My suggestion for the developers is to htmlspecialchars() the php dump and place it within a textarea for easy viewing/copying. Otherwise, the embedded comment tags will either have to be stripped or encoded somehow.

**Comment by Misplon** [comment]
Hey @danFWD thanks for raising this. What we'll do is introduce a change to Page Builder 2.5 that will allow you to register JSON layouts. That way you can build your prebuilt, click Layouts > Export and download the JSON file and then register it as the theme level prebuilt layout. We expect to launch version 2.5 beta to developers next week. The developer newsletter signup form is [here](http://siteorigin.us1.list-manage.com/subscribe?u=22e0c978d464421794fc99304&id=27212eb160), we'll let everyone know when it's out. Thanks for your support.

**Comment by gregpriday** [comment]
This is the specific issue that'll remove our need for the data dump https://github.com/siteorigin/siteorigin-panels/issues/135

I'm starting on this now.

**Comment by danFWD** [comment]
Sounds like a much better plan. Thanks for your hard work!

**Comment by danFWD** [comment]
Hello, to follow up on this, I see that there is now a way to export and import a layout in JSON format with the 2.5 update. I was just wondering, can we use those JSON files to register a pre-built layout so that it's selectable in the Theme Defined layouts panel?

**Comment by Misplon** [comment]
Sorry for the delay, Greg will hit us up with the new inclusion method as soon as he has a moment to spare. I'll follow-up as soon as I know more.

**Comment by danFWD** [comment]
Okay, great. I'm trying at the moment to use the 'pb_custom_prebuilt_layouts' filter with  file_get_contents and then json_decode on the exported JSON files. So far, no luck getting it to register.

**Comment by suganyaselvakumar** [comment]
I got it,
function mytheme_prebuilt_layouts($layouts){
    $layouts['home-page'] = array(
        // We'll add a title field
        'name' => __('Default Home', 'vantage'),    // Required
        'description' => __('Default Home Description', 'vantage'),    // Optional
        'screenshot' => plugin_dir_url( __FILE__ ) . 'images/layout-screenshot.png',    // Optional
        'filename' => get_template_directory()  . '/jsonfile.json', 
    );
    return $layouts;

}
add_filter('siteorigin_panels_prebuilt_layouts','mytheme_prebuilt_layouts');

**Comment by Misplon** [comment]
Hi :) If anyone is still interested, this can now be done by exporting a JSON layout and then including it as follows:

https://github.com/siteorigin/siteorigin-corp/blob/develop/inc/siteorigin-panels.php#L11-L18

https://github.com/siteorigin/siteorigin-corp/tree/develop/inc/layouts

Hope that helps.

All the best.
