### ISSUE TITLE
Link to 404 page in docs/widgets-bundle/form-building/adding-custom-fields.md

### ISSUE THREAD

**Issue by jnhghy** [siteorigin/docs#18]
The first link in the file: https://github.com/siteorigin/so-dev-examples/tree/develop/extend-widgets-bundle/custom-fields/ takes me to a 404.

Thanks

**Comment by braamgenis** [comment]
Hi Jalexandru

Thanks for letting us know. I've fixed this in the develop branch.

Cheers
Braam
