### ISSUE TITLE
Add info and line field 

### ISSUE THREAD

**Issue by fingerprintweb** [siteorigin/docs#21]
Hi!

I think in https://siteorigin.com/docs/widgets-bundle/form-building/form-fields/ we need element where we can add info for clients and line to separate fields.

**Comment by Misplon** [comment]
Hi @fingerprintweb Sorry we weren't able to reply at the time of posting. If you would still like this feature, please can you post a feature request on the Widgets Bundle repo: https://github.com/siteorigin/so-widgets-bundle/issues. Thanks.
