### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by ziga-miklic** [siteorigin/docs#3]
You get these errors when activating the examples:

```php
Fatal error: Class 'SiteOrigin_Widget_MyAwesomeWidget_Widget' not found in C:\xampp2\htdocs\dropout-wp\wp-includes\widgets.php on line 560

Fatal error: Class 'SiteOrigin_Widget_HelloWorldWidget_Widget' not found in C:\xampp2\htdocs\dropout-wp\wp-includes\widgets.php on line 560

Fatal error: Class 'SiteOrigin_Widget_WidgetFormFields_Widget' not found in C:\xampp2\htdocs\dropout-wp\wp-includes\widgets.php on line 560
```

To make it work you have to rename them to:

Widget_Form_Fields
SiteOrigin_Widget_WidgetFormFields_Widget

My_Awesome_Widget
SiteOrigin_Widget_MyAwesomeWidget_Widget

Hello_World_Widget
SiteOrigin_Widget_HelloWorldWidget_Widget

The issue is with the siteorigin_widget_register function:
```php
function siteorigin_widget_register($name, $path){
	global $siteorigin_widgets_registered, $siteorigin_widgets_classes;
	$siteorigin_widgets_registered[$name] = realpath( $path );
	$siteorigin_widgets_classes[] = 'SiteOrigin_Widget_' . str_replace( ' ', '', ucwords( str_replace('-', ' ', $name) ) ) . '_Widget';
}
```

This is because the function wraps all the newly added widgets with: SiteOrigin_Widget_"widget_name"_Widget and removes "-", which are used in the naming of the examples:

```php
siteorigin_widget_register('hello-world-widget', __FILE__, 'Hello_World_Widget');
siteorigin_widget_register('my-awesome-widget', __FILE__, 'My_Awesome_Widget');
siteorigin_widget_register('widget-form-fields', __FILE__, 'Widget_Form_Fields');
```

I opened a ticket instead of changing anything, because I am not sure how you will solve the issue.

Possible solutions:

Change the docs, so that developers know that they have to wrap their classes with your naming and watch out to not use "-" in widget names. 

Or edit the siteorigin_widget_register function, but that means you will also need to rename your widgets inside the SiteOrigin Extend Widgets Bundle Plugin.

Sorry for the wall of text, I hope I did not miss anything or made an issue out of nothing.

**Comment by braamgenis** [comment]
Hi ziga

Thanks so much for your input and it's definitely not nothing!

We have the ability in the develop branch to optionally supply your custom class name as a 3rd argument for `siteorigin_widget_register`. So the dev examples were just slightly ahead of their time. ;) This change should now be available in the master branch too.
