### ISSUE TITLE
Broken page in repo

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [siteorigin/docs#41]
documentation in this page is broken. https://github.com/siteorigin/docs/blob/develop/widgets-bundle/advanced-concepts/actions/initialize-widget.md

**Comment by Misplon** [comment]
Thanks for letting us know. Sorry it took so long to reply. I'll try get this fixed ASAP.

**Comment by Misplon** [comment]
Thanks @PrafullaKumarSahu. Resolved via: https://github.com/siteorigin/docs/pull/47. If you'd like any further clarification, please let us know. Sorry we couldn't reply at the time.
