### ISSUE TITLE
Site Origin Editor Read More Option

### ISSUE THREAD

**Issue by PremalathaKumar** [siteorigin/docs#43]
Hi all,

I'm using Site Origin Page Builder for my site. 
It works well. But the thing is when I added site origin editor widget read more option is not working.
May I know what to do. 
Thank you in advance!!

**Comment by Misplon** [comment]
Hi :) Thanks for posting. This isn't the best place for questions on the contents of the documentation. Issues here would be more for things like missing or incorrect documentation. Can you perhaps post an issue on the forum and send me the link, I'd be happy to take a look.

https://siteorigin.com/thread.

If you can provide a link to the page concerned, that would helpful :)
