### ISSUE TITLE
Widget is not showing up

### ISSUE THREAD

**Issue by alaksandarjesus** [siteorigin/docs#45]
Hi.. I am trying to follow your tutorial and my widget is not showing up in the list. I am litreally new to Wordpress customization.

**functions.php**

```
function add_my_awesome_widgets_collection($folders) {
	$folders[] = __DIR__ . '/barter-widgets';
	return $folders;
}
add_filter('siteorigin_widgets_widget_folders', 'add_my_awesome_widgets_collection');
```

```

<?php

/*
Widget Name: Barter Login Widget
Description: A widget that allows the user to login
Author: Alaksandar Jesus Gene
 */

class Barter_Login_Widget extends SiteOrigin_Widget {

	function __constructor() {
		echo "Hello I am run from constructor";
	}

	function get_template_name($instance) {
		return '';
	}

	function get_style_name($instance) {
		return '';
	}
}

siteorigin_widget_register('barter-login-widget', __FILE__, 'Barter_Login_Widget');

```

![1](https://user-images.githubusercontent.com/4712552/39364779-b333ec60-4a4c-11e8-8de3-279e62d92de7.JPG)
![2](https://user-images.githubusercontent.com/4712552/39364780-b3763688-4a4c-11e8-8234-b4611a604bc1.JPG)

**Comment by AlexGStapleton** [comment]
Hi alaksandarjesus,

To confirm, which list are you referring to? The Add Widget list or your widgets list (**WP Admin > Plugins > SiteOrgin Widgets**)? If the former, please navigate to your widgets lists and activate the widget. If the latter, can you please provide me with the full Better-widgets directory so I can run some tests against it?
