### ISSUE TITLE
Write a guide on how to use siteorigin_panels_local_layouts_directories

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/docs#53]
We need to write a guide on how to use [siteorigin_panels_local_layouts_directories](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/admin-layouts.php#L82).

[Related](https://siteorigin.com/thread/page-builder-save-custom-layouts-into-layouts-directory/)

**Comment by AlexGStapleton** [comment]
@Misplon I just went to start on this and it appears you actually did this [last November](https://github.com/siteorigin/docs/commit/9ed0bc22155d5ab9bd42137f9f5990717371728a#diff-6d7408b838610fa4c77d2a6cb1f442c6).

https://siteorigin.com/docs/page-builder/bundling-prebuilt/

Was there anything you felt missing, or are you okay with closing this issue?

**Comment by Misplon** [comment]
Thanks for checking, closing.
