### ISSUE TITLE
Incorrect link in documentation

### ISSUE THREAD

**Issue by aberkow** [siteorigin/docs#94]
On the [Enqueue Frontend Scripts Action page](https://siteorigin.com/docs/widgets-bundle/advanced-concepts/actions/enqueue-frontend-scripts/), there's a link to the Initializing a Widget page. However, that link is broken. It goes to [https://siteorigin.com/docs/widgets-bundle/getting-started/initializing-a-widget/](https://siteorigin.com/docs/widgets-bundle/getting-started/initializing-a-widget/) rather than [https://siteorigin.com/docs/widgets-bundle/getting-started/initialising-a-widget/](https://siteorigin.com/docs/widgets-bundle/getting-started/initialising-a-widget/). The first link has the correct spelling of the word "initializing" in the URL, but the second is the one that actually works.

**Comment by Misplon** [comment]
Thanks, Adam. Appreciate you logging this. Sorry for the hassle. We'll get this sorted this week.

**Comment by aberkow** [comment]
thanks very much 🙂
