### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError in Creating a Widget tutorial

### ISSUE THREAD

**Issue by tim-andes** [siteorigin/docs#96]
https://imgur.com/a/UllbvEj

docs > widgets-bundle > getting-started >creating-a-widget.md in siteorigin:develop

Following the Creating a Widget tutorial and, when it says I should now see an 'Untitled Widget', in Plugins>SiteOrigin Widgets, errors are thrown (see copy pasta below/screenshot above) at that page.

I am finding that if I comment out the code block in the Widget Class section and refresh, the errors go away.

As far as following the tutorial, I personalized the metadata in the widget .php file, but did not alter the class extension code block at all as it doesn't say that you need to.
__________
Fatal error: Uncaught ArgumentCountError: Too few arguments to function SiteOrigin_Widget::__construct(), 0 passed in /Users/timandes/Local Sites/tim-andes-test/app/public/wp-content/plugins/so-widgets-bundle/so-widgets-bundle.php on line 645 and at least 2 expected in /Users/timandes/Local Sites/tim-andes-test/app/public/wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php on line 53

ArgumentCountError: Too few arguments to function SiteOrigin_Widget::__construct(), 0 passed in /Users/timandes/Local Sites/tim-andes-test/app/public/wp-content/plugins/so-widgets-bundle/so-widgets-bundle.php on line 645 and at least 2 expected in /Users/timandes/Local Sites/tim-andes-test/app/public/wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php on line 53

**Comment by AlexGStapleton** [comment]
Based on the error message it appears you've added the widgets code directly to the main so-widgets-bundle.php file. Is that correct? If so, that will cause you issues. Please create a basic plugin, or child theme and then [point to a widgets directory](https://siteorigin.com/docs/widgets-bundle/getting-started/creating-a-widget/#heading-registering-a-custom-widgets-folder) for that plugin/theme and put your widgets there.

Regardless of the above, can you please provide me with a copy of the widget code you're using? Please note that that this guide is a step by step process so you're not able to copy and paste one of the code examples and have it work. You'll need to follow the guide along and make the suggested code changes.

**Comment by tim-andes** [comment]
Nope! I have not yet accessed/altered any SiteOrigin files and did not add any code to so-widgets-bundle.php.

I'm working in a child theme and have, within functions.php:
```
<?php
/**
 * Camerawork-child Theme functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package camerawork-child
 */

add_action( 'wp_enqueue_scripts', 'siteorigin_corp_parent_theme_enqueue_styles' );

/**
 * Enqueue scripts and styles.
 */
function siteorigin_corp_parent_theme_enqueue_styles() {
	wp_enqueue_style( 'siteorigin-corp-style', get_template_directory_uri() . '/style.css' );
	wp_enqueue_style( 'camerawork-child-style',
		get_stylesheet_directory_uri() . '/style.css',
		array( 'siteorigin-corp-style' )
	);

}

/**
 * Widgets - TA.04-06-2021
 */

// Register custom widgets folder
function add_cw_widgets( $folders ){
    $folders[] = plugin_dir_path(__FILE__).'widgets/';
    return $folders;
}

add_filter( 'siteorigin_widgets_widget_folders', 'add_cw_widgets');

```
Within my widgets folder, I have image-banner.php with:

```
<?php

/*
Widget Name: Image Banner
Description: Practice for extending SiteOrigin widgets.
Author: Tim Andes
*/

class Image_Banner_Widget extends SiteOrigin_Widget {

    function get_template_name( $instance ) {
        return "";
    }

    function get_style_name( $instance ) {
        return "";
    }
}

siteorigin_widget_register( "image-banner", __FILE__, "Image_Banner_Widget" );
```

**Comment by AlexGStapleton** [comment]
> Nope! I have not yet accessed/altered any SiteOrigin files and did not add any code to so-widgets-bundle.php.

Thanks for clarifying.

The issue your facing is that your class is incomplete. [it's missing the widget class constructor](https://siteorigin.com/docs/widgets-bundle/getting-started/creating-a-widget/#heading-widget-class-constructor). I've checked the relevant doc and it mentions what you're using as valid, but it's not. I'll correct this in the morning.

To be clear, this is incorrect:

> Once you've done this, you'll see your widget in the Plugins > SiteOrigin Widgets list, it can be activated and deactivated, and you'll see an 'Untitled Widget' in Page Builder widgets and a blank widget in other widget lists. So you can't really use your widget yet, but it's there!

**Comment by Misplon** [comment]
Hi Tim

When you have a moment, perhaps check that the Corp parent stylesheet isn't being loaded twice. The parent theme will enqueue the minified theme stylesheet so it should only be necessary to enqueue the child's stylesheet. The below is from our Corp child starter theme:

```
function siteorigin_corp_child_scripts() {

	// Child theme stylesheet.
	wp_enqueue_style( 'corp-child', get_stylesheet_directory_uri() . '/style.css' );

}
add_action( 'wp_enqueue_scripts', 'siteorigin_corp_child_scripts', 8 );
```

Thanks

**Comment by tim-andes** [comment]
Screenshot: [https://imgur.com/a/DfWpcfw](url)

To clarify, should I *not* see any child theme stylesheet? I have one Corp and one child theme css file showing up

**Comment by Misplon** [comment]
The last file in the list is the minified version of the file you have selected in the screenshot. Only the minified version is required.

**Comment by tim-andes** [comment]
Got it. I removed the enqueue for Corp stylesheet and left the child theme enqueue.  I'll await Alex's docs adjustment and try it again tomorrow

**Comment by AlexGStapleton** [comment]
@tim-andes I've submitted a PR containing an updated Widget Class section [here](https://github.com/siteorigin/docs/pull/97).
